version: '3'

services:
  app:
    build: .
    container_name: api-vdt_chamada_taxista
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/adpp

  db:
    container_name: db-vdt_chamada_taxista
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vdtch@m@d@taxista
      - MYSQL_DATABASE=vdt_chamada_taxista
