version: '3'

services:
  app:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: api-nestjs-template
    tty: true
    volumes:
      - .:/home/node/app
      - .:/home/node/app/node_modules
    command: npm run start:dev
    ports:
      - '5555:5555'
    restart: always
    env_file:
      - ./src/common/envs/development.env
    depends_on:
      - db

  db:
    container_name: db-nestjs-template
    image: mysql
    tty: true
    ports:
    - '3306:3306'
    restart: always
    env_file:
      - ./src/common/envs/development.env
volumes:
  db-data: {}
