version: '3'

services:
  app:
    image: node:lts-alpine
    build: .
    container_name: vdt_hub_b2b
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/adpp
    environment:
      - NODE_ENV=development
