version: '3'

services:
  app:
    container_name: vdt_hub_b2b
    image: node:lts-alpine
    build: .
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=development
