version: '3'

services:
  app:
    container_name: vdt-hub-b2b
    build: .
    volumes:
      - .:/home/node/app
      - .:/home/node/app/node_modules
    command: npm run start:dev
    ports:
      - '5555:5555'
    env_file:
      - ./src/common/envs/development.env
